### ISSUE TITLE
release code?

### ISSUE THREAD

**Issue by loboere** [curryjung/VisualStylePrompt#1]
incredible work, could you give a date for when the code will be released and also how much ram and vram is used

**Comment by curryjung** [comment]
The code will be uploaded this week. 

 If you can infer with num-of-samples==2 using SDXL, you will be fine.

ControlNet is also provided and could demand more memory to upload the additional weights.

Thank you.

**Comment by Mr-Jin2** [comment]
@curryjung  Do you have a schedule release code? I I have reproduced the paper, but the result is unsatisfactory. I want to know where the problem lies.
Thank you.

**Comment by loboere** [comment]
It's been more than a week, when are they going to upload the code?

**Comment by YUHANG-Ma** [comment]
Hi, it's really a stunning work!! Could I ask when you could release your code? I also tried to reproduced the paper but the result failed to meet expectations. Looking forward to your reply and code. @curryjung

**Comment by curryjung** [comment]
Sorry for the late release of the code. I just got a notice that the inspection is done. It will be uploaded in 24 hours. Thx

**Comment by edtjulien** [comment]
Don't be sorry! It's so great you open-source and release it 👏

**Comment by loboere** [comment]
It's been more than a 24hs, when are they going to upload the code?

**Comment by whhamber** [comment]
I like this work! Looking forward to the code.

**Comment by curryjung** [comment]
Now code is available :)

**Comment by edtjulien** [comment]
Thank you!!
