### ISSUE TITLE
Does this need training?

### ISSUE THREAD

**Issue by Mr-Jin2** [curryjung/VisualStylePrompt#2]
amazing work! but I have some questions.
I noticed that the paper mentioned "This approach allows for the visual style prompting without any fine-tuning, ensuring that generated images maintain a faithful style.", but what confuses me is:
 1. where the "conv" comes from?
 2. How can I get reference features?

![微信截图_20240227120917](https://github.com/curryjung/VisualStylePrompt/assets/38421253/33c29a0f-d0f2-4cda-88e6-2e3d536b169b)
Thank you.

**Comment by curryjung** [comment]
1. conv represents Q,K and V matrix which reside in attention block.
2. reference features come both from generation process or inversion
process.

The code will be realise soon, which will be helpful for you to understand
the prompting.

Thank you



2024년 2월 27일 (화) 오후 1:11, Mr-Jin2 ***@***.***>님이 작성:

**Comment by Mr-Jin2** [comment]
Thanks for your reply!
